name: Build and Test

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ fromJSON(vars.CI_RUNNER_LABELS) }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout tree
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.5"

      - name: Build and install dependencies
        run: opam install .

      # The Makefile explains why we don't use --with-test.
      - name: Install test dependencies
        run: opam exec -- make install-test-deps

      - name: Run build @all
        run: opam exec -- make all

      - name: Run the unit tests
        run: opam exec -- make test-ocaml
