name: Changelog check

on:
  workflow_dispatch:

jobs:
  Changelog-Entry-Check:
    name: Check Changelog Action
    runs-on: ${{ fromJSON(vars.CI_RUNNER_LABELS) }}
    steps:
      - uses: tarides/changelog-check-action@v4
